hull:
  objects:
    deployment:
      controller:
        pod:
          containers:
            controller:
              image:
                registry: k8s.gcr.io
                repository: ingress-nginx/controller
                tag: "v1.0.4"

