hull:
  config:
    specific:
      controller:
        configMaps:
          tcp:
            mappings: {}
          udp:
            mappings: {}
  objects:
    configmap:
      addheaders:
        enabled: "_HULL_TRANSFORMATION_<<<NAME=hull.util.transformation.bool>>><<<CONDITION=
          (index . \"PARENT\").Values.hull.objects.configmap.addheaders.data>>>"
        data: {}
      proxyheaders:
        enabled: "_HULL_TRANSFORMATION_<<<NAME=hull.util.transformation.bool>>><<<CONDITION=
          (index . \"PARENT\").Values.hull.objects.configmap.proxyheaders.data>>>"
        data: {}
      tcp:
        enabled: "_HULL_TRANSFORMATION_<<<NAME=hull.util.transformation.bool>>><<<CONDITION=
          (index . \"PARENT\").Values.hull.config.specific.controller.configMaps.tcp.mappings>>>" 
        data: 
          _HULL_TRANSFORMATION_:
            NAME: hull.util.transformation.tpl
            CONTENT: "
              {
              {{ range $key,$value :=  (index . \"PARENT\").Values.hull.config.specific.controller.configMaps.tcp.mappings }}
              {{ $key }}: { inline: {{ $value }} },
              {{ end }}
              }"
      udp:
        enabled: "_HULL_TRANSFORMATION_<<<NAME=hull.util.transformation.bool>>><<<CONDITION=
          (index . \"PARENT\").Values.hull.config.specific.controller.configMaps.udp.mappings>>>" 
        data:
          _HULL_TRANSFORMATION_:
            NAME: hull.util.transformation.tpl
            CONTENT: "
              {
              {{ range $key,$value :=  (index . \"PARENT\").Values.hull.config.specific.controller.configMaps.udp.mappings }}
              {{ $key }}: { inline: {{ $value }} },
              {{ end }}
              }"
      controller:
        data:
          add-headers:
            enabled: "_HULL_TRANSFORMATION_<<<NAME=hull.util.transformation.bool>>><<<CONDITION=
              (index . \"PARENT\").Values.hull.objects.configmap.addheaders.data>>>"
            path: files/add-headers
          set-proxy-headers:
            enabled: "_HULL_TRANSFORMATION_<<<NAME=hull.util.transformation.bool>>><<<CONDITION=
              (index . \"PARENT\").Values.hull.objects.configmap.proxyheaders.data>>>"
            inline: "_HULL_TRANSFORMATION_<<<NAME=hull.util.transformation.tpl>>><<<CONTENT=
              {{ (index . \"PARENT\").Release.Namespace }}/{{ include \"hull.metadata.fullname\" (dict \"PARENT_CONTEXT\" (index . \"PARENT\") \"COMPONENT\" \"proxyheaders\") }}>>>"
          allow-snippet-annotations:
            inline: "true"
          dhparam.pem:
            enabled: "_HULL_TRANSFORMATION_<<<NAME=hull.util.transformation.bool>>><<<CONDITION=
              (index (index . \"PARENT\").Values.hull.objects.secret.dhparam.data \"dhparam.pem\").inline>>>"
            inline: "_HULL_TRANSFORMATION_<<<NAME=hull.util.transformation.tpl>>><<<CONTENT=
              {{ (index (index . \"PARENT\").Values.hull.objects.secret.dhparam.data \"dhparam.pem\").inline }}>>>"
    secret:
      dhparam:
        enabled: "_HULL_TRANSFORMATION_<<<NAME=hull.util.transformation.bool>>><<<CONDITION=
          (index (index . \"PARENT\").Values.hull.objects.secret.dhparam.data \"dhparam.pem\").inline>>>"
        data: 
          dhparam.pem: 
